Sales Forecasting Application/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Sales_Forecasting_Application.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Sales Forecasting Application/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using Sales_Forecasting_Application.Model;
using Sales_Forecasting_Application.Model.DataContext;
using Sales_Forecasting_Application.Model.DTO_s;
using System.Text;

namespace Sales_Forecasting_Application.Pages
{
    public class IndexModel : PageModel
    {
        private readonly SalesDBContext _context;

        public IndexModel(SalesDBContext context)
        {
            _context = context;
        }

        public List<OrdersDTO> Sales { get; set; }
        public int selcted_Year { get; set; }
        public decimal TotalSales { get; set; }
        public decimal TotalSalesAfterInc { get; set; }
        public decimal Increment { get; set; }
        public List<OrdersDTO> Incsales { get; set; }
        [TempData]
        public string TempIncData { get; set; }
        [TempData]
        public string TempIncrement { get; set; }

        public async Task OnPostAsync(int year,decimal increment)
        {
            selcted_Year = year;
            var totalSalesData = await _context.Products
                .Where(p => p.Order.OrderDate.Year == year)
                .GroupBy(p => p.Order.State)
                .Select(g => new
                {
                    State = g.Key,
                    TotalSales = g.Sum(p => p.Sales)
                }).ToListAsync();

            var returnSalesData = await (from p in _context.Products
                                         join r in _context.OrdersReturns on p.OrderId equals r.OrderId
                                         join o in _context.Orders on r.OrderId equals o.OrderId
                                         where o.OrderDate.Year == year
                                         group p by o.State into g
                                         select new
                                         {
                                             State = g.Key,
                                             ReturnSales = g.Sum(p => p.Sales)
                                         }).ToListAsync();

            var salesData = totalSalesData
                .Select(ts => new OrdersDTO
                {
                    State = ts.State,
                    Orders = (decimal)(ts.TotalSales - (returnSalesData.FirstOrDefault(rs => rs.State == ts.State)?.ReturnSales ?? 0))
                }).OrderBy(s => s.State).ToList();

            Sales = salesData;
            TotalSales = salesData.Sum(s => s.Orders);

            if (increment != 0)
            {
                Increment = increment;
                TempIncrement = JsonConvert.SerializeObject(increment);
                Incsales = Sales.Select(s => new OrdersDTO
                {
                    State = s.State,
                    Orders = s.Orders,
                    IncrementedSales = s.Orders * (1 + increment / 100)
                }).ToList();

                TempIncData = JsonConvert.SerializeObject(Incsales);
                TotalSalesAfterInc = Incsales.Sum(s => s.IncrementedSales);
            }

            
        }

        public IActionResult OnPostDownload()
        {
            Increment = JsonConvert.DeserializeObject<decimal>(TempIncrement);
            Incsales = JsonConvert.DeserializeObject<List<OrdersDTO>>(TempIncData);
            var csv = new StringBuilder();
            csv.AppendLine("State,Percentage Increase,Increased Sales");


            foreach(var sales in Incsales)
            {
                csv.AppendLine($"{sales.State},{Increment},{sales.IncrementedSales}");
            }

            return File(Encoding.UTF8.GetBytes(csv.ToString()), "text/csv", "Forecasted_Sales_Data.csv");
        }
    }
} 

Sales Forecasting Application/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sales_Forecasting_Application.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Sales Forecasting Application/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Sales Forecasting";
}

<h2>Sales Forecasting</h2>

<form class="form-inline" method="post">
    <label for="year">Select Year:</label>
    <select class="form-select mb-2 mr-sm-2" id="year" name="year">
        @for (int i = 2018; i <= 2021; i++)
        {
            <option value="@i">@i</option>
        }
    </select>
    <label class="form-label" for="increment">Percentage Increment:</label>
    <input type="number" class="form-control mb-2 mr-sm-2" id="increment" name="increment" step="0.1" min="0" />
    <button class="btn btn-success" type="submit">Query Sales</button>
</form>

@if (Model.Sales != null)
{
    <h4>Total Sales for @Model.selcted_Year</h4>
    <p>@Model.TotalSales.ToString("C")</p>
    @if(Model.Increment != 0)
    {
        <h4>Total Sales for @Model.selcted_Year after Incremenet</h4>
        <p>@Model.TotalSalesAfterInc.ToString("C")</p>
    }

    <h4>Sales Breakdown by State:</h4>
    @if(Model.Increment == 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>State</th>
                    <th>Sales</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Sales)
                {
                    <tr>
                        <td>@item.State</td>
                        <td>@item.Orders</td>
                    </tr>

                }
            </tbody>
        </table>
    }else
    {
        <table class="table">
            <thead>
                <tr>
                    <th>State</th>
                    <th>Old Sales</th>
                    <th>Incremented Sales</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Incsales)
                {
                    <tr>
                        <td>@item.State</td>
                        <td>@item.Orders</td>
                        <td>@item.IncrementedSales</td>
                    </tr>
                }
            </tbody>
        </table>

        <form method="post" asp-page-handler="Download">
            <button class="btn btn-danger" type="submit">Download Forecasted Data</button>
        </form>
    }
   
}

Sales Forecasting Application/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sales_Forecasting_Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sales_Forecasting_Application.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Sales_Forecasting_Application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sales_Forecasting_Application - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>